### DISCUSSION TITLE
github action to push theme to shopify

### DISCUSSION THREAD

**Discussion by tentree-development** [uicrooks/shopify-theme-lab#158] [Q&A]
Is it possible to add a github action here so eveyone can use

**Comment by OliverJEvans** [comment]
I use this action

https://github.com/bravetheskies/shopify-rapid-deploy-action


```
# When a commmit is pushed to the `main` branch deploy to production
name: Deploy to Production
on:
  push:
    branches:
      - develop # TODO - this may need updating

jobs:
  build:
    name: Deploy theme
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run webpack:build

      - name: Deploy theme
        uses: bravetheskies/shopify-rapid-deploy-action@v1
        env:
          SHOPIFY_APP_API_PASSWORD: ${{ secrets.SHOPIFY_APP_API_PASSWORD }}
          SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_THEME_ID }}
          THEME_PATH: ${{ secrets.SHOPIFY_THEME_PATH }}

```
