### ISSUE TITLE
Edits to duplicated theme spill over into currently published live theme

### ISSUE THREAD

**Issue by ryanhilton** [uicrooks/shopify-theme-lab#105]
Just as a preface, I’m a few versions behind release/version 3.

I apologize if I’m missing something, but I have duplicated a theme, (and updated the dev/live configs to use that new theme ID) and restarted all processes with the new config, however any changes I make go directly to the live (published theme).. that goes for styles, templates, pretty much every file.

We’re just baffled as to why the changes don’t only go to the new duplicated theme (that has the new ID in the config) it’s making it hard to work on edits since we don’t want the live site looking messed up.

If I make edits to files in the duplicated theme via the web editor they don’t leak over to the published theme, so I’m not sure what I have wrong.

Thank you,
Ryan

**Comment by sergejcodes** [comment]
I just recreated your setup and I don't have this issue, everything works as expected.

Have you updated the file names and keys? You should have two configs like this:

For your dev theme
```
.config/shopify/shopify.dev.yml
```

with the root key `dev`

```
dev:
  password: [your-api-password]
  theme_id: "[your-theme-id]"
  store: [your-store].myshopify.com
  directory: shopify
  ignores:
    - .config/shopify/.shopifyignore
```

For your live theme
```
.config/shopify/shopify.live.yml
```

with the root key `live`

```
live:
  password: [your-api-password]
  theme_id: "[your-theme-id]"
  store: [your-store].myshopify.com
  directory: shopify
  ignores:
    - .config/shopify/.shopifyignore
```
